### ISSUE TITLE
Add markdown processing

### ISSUE THREAD

**Issue by torstein-vik** [torstein-vik/zophie#37]
For instance something like \<markdown\> \</markdown\> which converts into a \<div\> with the html-version of the content of \<markdown\>. 

This should support latex.

Something like showdown would probably work, but first we have to resolve some security issues.

**Comment by thea-vik** [comment]
Added basic support w/ showdown, math remains

**Comment by thea-vik** [comment]
Added escaping of HTML characters. Still, javascript links are a problem, but not one which is easy to solve really.

**Comment by thea-vik** [comment]
Added MathJax support
