### ISSUE TITLE
Refresh sends you to reqlogin

### ISSUE THREAD

**Issue by torstein-vik** [torstein-vik/zophie#43]
Reproduce: refresh page on /addcontent when logged in. It sends you to /reqlogin, even though you are still logged in.

**Comment by thea-vik** [comment]
Upon inspection, this is a more general issue every time you go to a page which requires login directly using URL

**Comment by thea-vik** [comment]
I created a hacky solution to this. Not happy about it, but there doesn't appear to be a promise object for loading currentUser.
