### ISSUE TITLE
Implement 1st level of content-adding interface

### ISSUE THREAD

**Issue by andreasholmstrom** [torstein-vik/zophie#5]
See REQUIREMENTS-DETAILS.md

**Comment by thea-vik** [comment]
@andreas1729, How intelligent should Zophie be when deciding if two keywords are the same?

**Comment by andreasholmstrom** [comment]
The main problem is singular-plural, and I think that for example "ring" and "rings" should always be regarded as the same keyword. In real-world articles (with lists of keywords) both singular and plural are frequently used. But I guess it is not so easy to automatically detect that for example "topos", "topoi", and "toposes" are the same keyword. In any case, it's better with a quick-and-easy approach that works ok, than spending lots of time on this minor issue. 

We could perhaps have a system where whenever Zophie guesses that two keywords are the same, a user can manually confirm Zophie's guess in a separate interface.

**Comment by andreasholmstrom** [comment]
I cannot think of any other kind of situation where two keywords should be regarded as the same. It's just the singular-plural situation.

**Comment by thea-vik** [comment]
Regarding the singular-plural situation we could have Zophie guess and then ask if two things are the same. What about something like $Z$-module, Z-module, module over the integers, or ring? Shouldn't some of these be considered equivalent?

**Comment by andreasholmstrom** [comment]
Yes, the situation involving Z-module and $Z$-module should be considered the same. Maybe Zophie could guess this as well. As for the more complicated expressions (which surely are equivalent from a mathematical point of view), I don't think they will occur very often in practice, so there is no point spending time on this issue now.

PS. I guess you mean Z-algebra, not Z-module.

**Comment by thea-vik** [comment]
Guessing this issue is now closed, with the new specification outlined in first-prototype-sep2017.md
